### ISSUE TITLE
Update packaging

### ISSUE THREAD

**Issue by emdupre** [pauljaffe/openneuroglm#1]
It looks like you have the current package listed as a requirement in your `requirements.txt` :

https://github.com/pauljaffe/openneurofirstlevel/blob/dfb00b16f848683e81571e5bc06a2b04cf8ab381/requirements.txt#L5

This doesn't match your `setup.py` [`install_requires`](https://github.com/pauljaffe/openneurofirstlevel/blob/dfb00b16f848683e81571e5bc06a2b04cf8ab381/setup.py#L9-L17) field, so I assume that it's specific to your [Apptainer installation instructions](https://github.com/pauljaffe/openneurofirstlevel/blob/dfb00b16f848683e81571e5bc06a2b04cf8ab381/openneurofirstlevel.def#L5).

You could streamline all of this by moving to the more recent `pyproject.toml` package organization as recommended by Chris M:

https://effigies.gitlab.io/posts/python-packaging-2023/

There's this recent blogpost on optimizing docker builds with poetry (which `pyproject.toml` supports, pulled from [this thread](https://github.com/orgs/python-poetry/discussions/1879)):

https://medium.com/@albertazzir/blazing-fast-python-docker-builds-with-poetry-a78a66f5aed0

EDIT : I'm not sure that it's really worth adopting poetry, but focusing on the build time just seems like a side benefit ! Really, I'd focus first on not having to maintain dependencies in two spots 😸

**Comment by effigies** [comment]
A question I have is how you want to use this repository. This not quite an installable package, but the stated use on the README is just `python runfirstlevel.py ...`. If that's what it's intended to be, then you can just remove `openneurofirstlevel` from your `requirements.txt` and your `setup.py`, and you're set.

If you want to make it an installable package, you'll want to put your `runfirstlevel.py` either into the package as, e.g., `openneurofirstlevel/cli.py` or possibly into `scripts/`. And then you'll need to tell `setup.py` (or `pyproject.toml`) where to find your script so it can be installed.

In either case, I don't think you want an `__init__.py` in your repository root. The root is definitely not a Python module.

**Comment by pauljaffe** [comment]
thanks all - I've restructured the code to be a proper package, and moved the CLI to openneuroglm/cli.py
